apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-apricot-iguana
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
      kubevirt.io/domain: test-vm
    spec:
      domain:
        devices:
          disks:
            - name: rootdisk
              disk:
              bus: virtio
        resources:
          requests:
            memory: 2Gi
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk