apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - GPU # Ensure GPU feature gate is enabled
        # May also be relevant depending on KubeVirt version
        # - HostDevices
      permittedHostDevices:
        pciHostDevices:
          # Example: NVIDIA Tesla P4 (VendorID:DeviceID)
          - pciVendorSelector: "10DE:1BB3"
            # Must match device plugin advertisement
            resourceName: "nvidia.com/GP104GL_TESLA_P4"
            # Crucial when using vendor device plugins
            externalResourceProvider: true
            # Example: AMD Radeon Pro VII
          - pciVendorSelector: "1002:731F"
            resourceName: "amd.com/gpu"
            externalResourceProvider: true