apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: example-vm
spec:
  running: false
  template:
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 1Gi
        devices:
          disks:
            - name: mydisk
              disk:
                bus: virtio
              volumeName: mypvc
    volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: myclaim
...