apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: custom-bridge-net
  namespace: default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br0",
    "isGateway": true,
    "ipam": {
      "type": "static",
      "addresses": [{
        "address": "192.168.1.100/24",
        "gateway": "192.168.1.1"
      }]
    }
  }'